apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t3.large
    desiredCapacity: 1
    volumeSize: 30
  - name: ng-2
    instanceType: t3.large
    desiredCapacity: 1
    volumeSize: 30